=head1 NAME

fizsh - Fizsh is a user friendly front end to zsh. 

=head1 SYNOPSIS

fizsh [OPTIONS] ... [ARGUMENTS] ...

=head1 DESCRIPTION

Fizsh provides zsh with interactive syntax-highlighting and a MATLAB-like history-search. Fizsh is intended to look and feel similar to fish. A distinguishing feature is that fizsh can handle Bourne compatible syntax. This is because fizsh is a front end to zsh. Fish does not handle Bourne compatible syntax.

=head1 CONFIGURATION

"$HOME/.fizsh/" is the directory where fizsh keeps its local configuration files. The file "$HOME/.fizsh/.fizshrc" serves as the user's local startup script. Local customizations, such as aliases and functions, can be added here. This file allows the same syntax as "$HOME/.zshrc" under zsh. "$HOME/.fizsh/.fizsh_history" is the name of fizsh's history file. The other files in "$HOME/.fizsh" are installed when the user runs "/usr/bin/fizsh" for the first time. 

Individual users may use the functions "fizsh-upgrade", which will upgrade a user's B<local> configuration files to the latest versions available on the internet. The function "fizsh-reinstall" will overwrite these files again with the B<central> versions installed on the system. 

Compared to the default configuration of zsh, fizsh additionally sets the options "append_history", "inc_append_history", "hist_ignore_all_dups", "hist_reduce_blanks", "hist_ignore_space", "interactive_comments", "correct", "no_beep" and "prompt_subst".

For further configuration details consult zsh's man pages

=head1 OPTIONS

Fizsh is usually invoked without options and without command-line arguments. 

The only supported command-line options are currently "--version", "--help", "--login", shorthands for these commands are "-v", "-h", "-l" respectively. "--version" yields fizsh's version number. "--help" causes fizsh to print brief usage information. "--login" causes fizsh to be a login shell. 

If invoked with other command-line options and/or arguments fizsh will silently revert to zsh. Therefore, it is safe to use fizsh as one's login shell (.e.g. by using "chsh -s /usr/bin/fizsh").

=head1 BUGS

There are no known bugs at the moment. Bug reports, bug fixes and other comments are welcome.

=head1 NOTES

MATLAB is a registered trademark of The MathWorks, Inc.

=head1 AUTHOR

Guido van Steen, based on work by the "zsh-syntax-highlighting contributors" and the contributors to "zsh-history-substring-search". The also author gratefully acknowledges http://www.zsh.org/mla/users/2011/msg00734.html.

=head1 SEE ALSO

fizsh(1), fish(1), zsh(1)
